import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.navigation)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt.plugin)
}

android {
    compileSdk 35

    defaultConfig {
        applicationId "nz.co.test.transactions"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        compose true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.7.5"
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }
    namespace 'nz.co.test.transactions'

    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
}

dependencies {

    //Timber logging
    implementation libs.timber

    implementation libs.dagger.hilt.android
    implementation libs.androidx.junit.ktx
    ksp libs.hilt.compiler
    implementation (libs.hilt.navigation.compose)

    implementation libs.dagger
    ksp libs.dagger.compiler


    implementation libs.kotlin.stdlib
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    implementation libs.fragment.ktx

    implementation libs.retrofit
    implementation libs.retrofit.moshi
    implementation libs.moshi.kotlin

    implementation libs.coroutines.android
    implementation libs.coroutines.core
    implementation libs.coroutines.test

    //Testing libraries
    testImplementation libs.junit

    // JUnit 5 Core Dependencies
    testImplementation libs.junit.jupiter.api
    testImplementation libs.junit.jupiter.engine
    testImplementation libs.junit.jupiter.params

    testImplementation libs.ext.junit
    testImplementation libs.espresso.core
    testImplementation libs.mockito.inline
    testImplementation libs.mockito.kotlin
    // Kotlin Coroutines Testing Dependency
    testImplementation libs.coroutines.test
    // Truth Testing Dependency
    testImplementation libs.truth
    // Turbine Library Dependency
    testImplementation libs.turbine


    //Compose
    implementation platform(libs.compose.bom)
    implementation libs.ui
    implementation libs.androidx.material
    debugImplementation libs.androidx.ui.tooling
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.activity.compose
    implementation libs.androidx.ui.viewbinding
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.androidx.ui.test.junit4
    testImplementation platform(libs.compose.bom)
    testImplementation libs.androidx.ui.test.junit4
    implementation libs.androidx.runtime
    implementation libs.androidx.runtime.livedata
    implementation libs.androidx.runtime.rxjava2
    implementation libs.androidx.runtime.rxjava3
    implementation libs.androidx.foundation
}